spring:
  ### 数据源
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/mysql
    username: user
    password: password
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      minimum-idle: 1
      maximum-pool-size: 8
      auto-commit: true
      idle-timeout: 60000
      pool-name: HikariPool
      max-lifetime: 1800000
      connection-timeout: 30000
      connection-test-query: select 1
  redis:
    host: 127.0.0.1
    port: 6379
    database: 0
    lettuce:
      pool:
        min-idle: 1
        max-active: 8
        max-idle: 8
        max-wait: 3000
